# -*- coding: utf-8 -*-
"""fakefriend_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SDdvz2JgK08i33Sdx7kXkGSyGsX0y6-p
"""

from flask import Flask, render_template, redirect, url_for
from flask_bootstrap import Bootstrap
from flask_wtf import FlaskForm
from wtforms import Form, StringField, SubmitField, SelectField, BooleanField, validators
from wtforms.validators import DataRequired

class FakeFriend(Form):
    username = StringField('Username')
    fullname = StringField('Full Name')
    description = StringField('Description')
    private = BooleanField('It is private profile')
    profilepic = BooleanField('It has profile picture', [validators.DataRequired()])
    externalurl = BooleanField('It has external URL')
    followers = StringField('Number of Followers')
    follows = StringField('Number of Follows')
    posts = StringField('Number of Posts')
    check = SubmitField('Check!')

import numpy as np
from flask import Flask, render_template,request, flash
import pickle

app = Flask(__name__)

@app.route('/mainpage', methods=['GET', 'POST'])
def fakeafriend():
    form = FakeFriend(request.form)
    if request.method == 'POST' and form.validate():
        username = (form.username.data)
        fullname = (form.fullname.data)
        description = (form.description.data)
        private = (form.private.data)
        profilepic = (form.profilepic.data)
        externalurl = (form.externalurl.data)
        followers = (form.followers.data)
        follows = (form.follows.data)
        posts = (form.posts.data)
        print(username)
        print(fullname)
        print(description)
        print(private)
        print(profilepic)
        print(externalurl)
        print(followers)
        print(follows)
        print(posts)
        flash('Thanks for using our app! Lets check more accounts!')
        return redirect(url_for('mainpage'))
    return render_template('fakefriend.html', form=form)